config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'restaurants', to: 'restaurants#index'
  # get 'restaurants/new', to: 'restaurants#new'
  # post 'restaurants', to: 'restaurants#create'
  # get 'restaurants/:id', to: 'restaurants#show', as: 'restaurant'

  root to: 'restaurants#index'

  resources :restaurants, only: [ :index, :new, :create, :show ] do
    resources :reviews, only: [ :index, :new, :create ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true

 validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews


  end

  def new
    # @restaurant for action in simple form
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h2>All Restaurants</h2>

<% @restaurants.each do |restaurant| %>
<ul>
  <li>
    <%= restaurant.name %> |
    <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"  %>

  </li>
</ul>
<% end  %>

app/views/restaurants/new.html.erb
<h2>Add form for new restaurant</h2>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h2>Show one Restaurant</h2>
<ul>
  <li><%= @restaurant.name %></li>
  <li><%= @restaurant.address %></li>
  <li>
    <% if @restaurant.phone_number  %>
      <%= @restaurant.phone_number %>
    <% else  %>
      <%= "no phone number given" %>
    <% end %>

  </li>
  <li><%= @restaurant.category %></li>



<hr>
  <%= link_to "See reviews", restaurant_reviews_path(@restaurant), class: "btn btn-primary" %>
  <%= link_to "Back to all restaurants", restaurants_path, class: "btn btn-primary" %>
</ul>

app/views/reviews/index.html.erb
<h1>Reviews of <%= @restaurant.name %></h1>

  <% if @restaurant.reviews[0].nil?  %>
    <%= "no reviews yet" %>
  <% else  %>
    <% @reviews.each do |review| %>
      <ul>
        <li><%= review.content %></li>
      </ul>
    <% end  %>
  <% end %>

  <%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary"  %>

  <%= link_to "Back to restaurant", restaurant_path(@restaurant), class: "btn btn-primary"  %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, input_html: { type: 'number' } %>
  <!-- type number added when params permission did not work but unnecessary -->

  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>